config/routes.rb
Rails.application.routes.draw do

  resource :user_sessions

  root 'user_sessions#new'

  get 'login' => 'user_sessions#new', :as => :login

  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :acompanamientos

  get 'welcome' => 'welcome#index', :as => :welcome

  resources :usuarios

  resources :sodas

  resources :snacks

  resources :platos

  resources :comentarios

end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario was successfully created.' }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:comentario, :puntos, :usuario_id, :plato_id)
    end
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comentario %><br>
    <%= f.text_field :comentario %>
  </div>
  <div class="field">
    <%= f.label :puntos %><br>
    <%= f.number_field :puntos %>
  </div>
  <div class="field">
    <%= f.label :usuario_id %><br>
    <%= f.number_field :usuario_id %>
  </div>
  <div class="field">
    <%= f.label :plato_id %><br>
    <%= f.number_field :plato_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<!--

    ?xml version="1.0" encoding="UTF-8" ?

    -->
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
    <html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" version="-//W3C//DTD XHTML 1.1//EN">
        <head>
            <link title="Default" href="/s/b0dcca.css" type="text/css" rel="stylesheet"></link>
            <title></title>
            <meta content="IE=edge" http-equiv="X-UA-Compatible"></meta>
            <link type="image/x-icon" href="/s/919f27.ico" rel="shortcut icon"></link>
            <link type="image/x-icon" href="/s/919f27.ico" rel="icon"></link>
            <%= stylesheet_link_tag "xkcd.css" %>
            <link href="/atom.xml" title="Atom 1.0" type="application/atom+xml" rel="alternate"></link>
            <link href="/rss.xml" title="RSS 2.0" type="application/rss+xml" rel="alternate"></link>
            <script async="" src="//www.google-analytics.com/analytics.js"></script>
            <script></script>
            <script src="//xkcd.com/1350/jquery.min.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/json2.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/cdn_time.js" type="text/javascript"></script>
            <style type="text/css"></style>
        </head>
        <body>
            <div id="topContainer">
                <div id="topLeft">
                    <ul>
                        <li>
                            

                                <%= link_to 'Sodas', sodas_path %>

                           
                        </li>
                        <li>
                            

                                <%= link_to 'Platos', platos_path %>

                            
                        </li>
                        <li>
                           

                                <%= link_to 'Snacks', snacks_path %>

                            
                        </li>
                        <li>
                           

                                <%= link_to 'Comentarios', comentarios_path %>

                           
                        </li>
                        <li>
                         

                                <%= link_to 'Usuarios', usuarios_path %>

                           
                        </li>
                        <li>

                                <%= link_to 'Extras', acompanamientos_path %>

                        </li>
                    </ul>
                </div>
                <div id="topRight">
                    <div id="masthead">
                        <span>                                
                           <!--img width="185" height="83" alt="xkcd.com logo" src="http://imgs.xkcd.com/static/terrible_small_logo.png"-->
                           <%= link_to(image_tag("UmenU 1.png", size: "185x120"), welcome_path) %>
                        </span>
                        <span id="slogan">

                            ¿No sabés dónde comer?

                            <br>

                             ¡Encontrá algo acá!

                        </span>
                    </div>
                    <div id="news">
                        
                    </div>
                </div>
                <div id="bgLeft" class="bg box"></div>
                <div id="bgRight" class="bg box"></div>
            </div>
            <div id="middleContainer" class="box">
                <div id="ctitle">

                    Comentario

                </div>
                
                <div id="comic">
                  
                    <%= render 'form' %>

                </div>
                <ul class="comicNav">
                    <li>
                            

                                <%= link_to 'Mostrar', @comentario %> 

                           
                        </li>
                        <li>
                            

                                <%= link_to 'Atrás', comentarios_path %>

                            
                        </li>
                </ul>
                <br>


                //ALGÚN COMENTARIO IMPORTANTE


                
                <div id="transcript" style="display: none"></div>
            </div>

           
            
        </body>
        <!--

         Layout by Ian Clasbey, davean, and chromakode 

        -->
    </html>

app/views/comentarios/index.html.erb
<!--

    ?xml version="1.0" encoding="UTF-8" ?

    -->
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
    <html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" version="-//W3C//DTD XHTML 1.1//EN">
        <head>
            <link title="Default" href="/s/b0dcca.css" type="text/css" rel="stylesheet"></link>
            <title></title>
            <meta content="IE=edge" http-equiv="X-UA-Compatible"></meta>
            <link type="image/x-icon" href="/s/919f27.ico" rel="shortcut icon"></link>
            <link type="image/x-icon" href="/s/919f27.ico" rel="icon"></link>
            <%= stylesheet_link_tag "xkcd.css" %>
            <link href="/atom.xml" title="Atom 1.0" type="application/atom+xml" rel="alternate"></link>
            <link href="/rss.xml" title="RSS 2.0" type="application/rss+xml" rel="alternate"></link>
            <script async="" src="//www.google-analytics.com/analytics.js"></script>
            <script></script>
            <script src="//xkcd.com/1350/jquery.min.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/json2.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/cdn_time.js" type="text/javascript"></script>
            <style type="text/css"></style>
        </head>
        <body>
            <div id="topContainer">
                <div id="topLeft">
                    <ul>
                        <li>
                            

                                <%= link_to 'Sodas', sodas_path %>

                           
                        </li>
                        <li>
                            

                                <%= link_to 'Platos', platos_path %>

                            
                        </li>
                        <li>
                           

                                <%= link_to 'Snacks', snacks_path %>

                            
                        </li>
                        <li>
                           

                                <%= link_to 'Comentarios', comentarios_path %>

                           
                        </li>
                        <li>
                         

                                <%= link_to 'Usuarios', usuarios_path %>

                           
                        </li>
                        <li>

                                <%= link_to 'Extras', acompanamientos_path %>

                        </li>
                    </ul>
                </div>
                <div id="topRight">
                    <div id="masthead">
                        <span>                                
                           <!--img width="185" height="83" alt="xkcd.com logo" src="http://imgs.xkcd.com/static/terrible_small_logo.png"-->
                           <%= link_to(image_tag("UmenU 1.png", size: "185x120"), welcome_path) %>
                        </span>
                        <span id="slogan">

                            ¿No sabés dónde comer?

                            <br>

                             ¡Encontrá algo acá!

                        </span>
                    </div>
                    <div id="news">
                        
                    </div>
                </div>
                <div id="bgLeft" class="bg box"></div>
                <div id="bgRight" class="bg box"></div>
            </div>
            <div id="middleContainer" class="box">
                <div id="ctitle">

                    Comentarios

                </div>
                
                <div id="comic">
                  
                    <table>
                      <thead>
                        <tr>
                          <th>Comentario</th>
                          <th>Puntos</th>
                          <th>Usuario</th>
                          <th>Plato</th>
                          <th colspan="3"></th>
                        </tr>
                      </thead>

                      <tbody>
                        <% @comentarios.each do |comentario| %>
                          <tr>
                            <td><%= comentario.comentario %></td>
                            <td><%= comentario.puntos %></td>
                            <td><%= comentario.usuario_id %></td>
                            <td><%= comentario.plato_id %></td>
                            <td><%= link_to 'Mostrar', comentario %></td>
                            <td><%= link_to 'Editar', edit_comentario_path(comentario) %></td>
                            <td><%= link_to 'Borrar', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>

                </div>
                <ul class="comicNav">
                        <li>
                            

                                <%= link_to 'Agregar comentario', new_comentario_path %>

                            
                        </li>
                </ul>
                <br>


                //ALGÚN COMENTARIO IMPORTANTE


                
                <div id="transcript" style="display: none"></div>
            </div>

           
            
        </body>
        <!--

         Layout by Ian Clasbey, davean, and chromakode 

        -->
    </html>

app/views/comentarios/new.html.erb
<!--

    ?xml version="1.0" encoding="UTF-8" ?

    -->
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
    <html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" version="-//W3C//DTD XHTML 1.1//EN">
        <head>
            <link title="Default" href="/s/b0dcca.css" type="text/css" rel="stylesheet"></link>
            <title></title>
            <meta content="IE=edge" http-equiv="X-UA-Compatible"></meta>
            <link type="image/x-icon" href="/s/919f27.ico" rel="shortcut icon"></link>
            <link type="image/x-icon" href="/s/919f27.ico" rel="icon"></link>
            <%= stylesheet_link_tag "xkcd.css" %>
            <link href="/atom.xml" title="Atom 1.0" type="application/atom+xml" rel="alternate"></link>
            <link href="/rss.xml" title="RSS 2.0" type="application/rss+xml" rel="alternate"></link>
            <script async="" src="//www.google-analytics.com/analytics.js"></script>
            <script></script>
            <script src="//xkcd.com/1350/jquery.min.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/json2.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/cdn_time.js" type="text/javascript"></script>
            <style type="text/css"></style>
        </head>
        <body>
            <div id="topContainer">
                <div id="topLeft">
                    <ul>
                        <li>
                            

                                <%= link_to 'Sodas', sodas_path %>

                           
                        </li>
                        <li>
                            

                                <%= link_to 'Platos', platos_path %>

                            
                        </li>
                        <li>
                           

                                <%= link_to 'Snacks', snacks_path %>

                            
                        </li>
                        <li>
                           

                                <%= link_to 'Comentarios', comentarios_path %>

                           
                        </li>
                        <li>
                         

                                <%= link_to 'Usuarios', usuarios_path %>

                           
                        </li>
                        <li>

                                <%= link_to 'Extras', acompanamientos_path %>

                        </li>
                    </ul>
                </div>
                <div id="topRight">
                    <div id="masthead">
                        <span>                                
                           <!--img width="185" height="83" alt="xkcd.com logo" src="http://imgs.xkcd.com/static/terrible_small_logo.png"-->
                           <%= link_to(image_tag("UmenU 1.png", size: "185x120"), welcome_path) %>
                        </span>
                        <span id="slogan">

                            ¿No sabés dónde comer?

                            <br>

                             ¡Encontrá algo acá!

                        </span>
                    </div>
                    <div id="news">
                        
                    </div>
                </div>
                <div id="bgLeft" class="bg box"></div>
                <div id="bgRight" class="bg box"></div>
            </div>
            <div id="middleContainer" class="box">
                <div id="ctitle">

                    Comentario nuevo

                </div>
                
                <div id="comic">
                  
                    <%= render 'form' %>

                </div>
                <ul class="comicNav">
                        <li>
                            

                                <%= link_to 'Atrás', comentarios_path %>

                            
                        </li>
                </ul>
                <br>


                //ALGÚN COMENTARIO IMPORTANTE


                
                <div id="transcript" style="display: none"></div>
            </div>

           
            
        </body>
        <!--

         Layout by Ian Clasbey, davean, and chromakode 

        -->
   </html>

app/views/comentarios/show.html.erb
<!--

    ?xml version="1.0" encoding="UTF-8" ?

    -->
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
    <html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" version="-//W3C//DTD XHTML 1.1//EN">
        <head>
            <link title="Default" href="/s/b0dcca.css" type="text/css" rel="stylesheet"></link>
            <title></title>
            <meta content="IE=edge" http-equiv="X-UA-Compatible"></meta>
            <link type="image/x-icon" href="/s/919f27.ico" rel="shortcut icon"></link>
            <link type="image/x-icon" href="/s/919f27.ico" rel="icon"></link>
            <%= stylesheet_link_tag "xkcd.css" %>
            <link href="/atom.xml" title="Atom 1.0" type="application/atom+xml" rel="alternate"></link>
            <link href="/rss.xml" title="RSS 2.0" type="application/rss+xml" rel="alternate"></link>
            <script async="" src="//www.google-analytics.com/analytics.js"></script>
            <script></script>
            <script src="//xkcd.com/1350/jquery.min.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/json2.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/cdn_time.js" type="text/javascript"></script>
            <style type="text/css"></style>
        </head>
        <body>
            <div id="topContainer">
                <div id="topLeft">
                    <ul>
                        <li>
                            

                                <%= link_to 'Sodas', sodas_path %>

                           
                        </li>
                        <li>
                            

                                <%= link_to 'Platos', platos_path %>

                            
                        </li>
                        <li>
                           

                                <%= link_to 'Snacks', snacks_path %>

                            
                        </li>
                        <li>
                           

                                <%= link_to 'Comentarios', comentarios_path %>

                           
                        </li>
                        <li>
                         

                                <%= link_to 'Usuarios', usuarios_path %>

                           
                        </li>
                        <li>

                                <%= link_to 'Extras', acompanamientos_path %>

                        </li>
                    </ul>
                </div>
                <div id="topRight">
                    <div id="masthead">
                        <span>                                
                           <!--img width="185" height="83" alt="xkcd.com logo" src="http://imgs.xkcd.com/static/terrible_small_logo.png"-->
                           <%= link_to(image_tag("UmenU 1.png", size: "185x120"), welcome_path) %>
                        </span>
                        <span id="slogan">

                            ¿No sabés dónde comer?

                            <br>

                             ¡Encontrá algo acá!

                        </span>
                    </div>
                    <div id="news">
                        
                    </div>
                </div>
                <div id="bgLeft" class="bg box"></div>
                <div id="bgRight" class="bg box"></div>
            </div>
            <div id="middleContainer" class="box">
                <div id="ctitle">

                    Comentario

                </div>
                
                <div id="comic">
                  
                  <p>
                    <strong>Comentario:</strong>
                    <%= @comentario.comentario %>
                  </p>

                  <p>
                    <strong>Puntos:</strong>
                    <%= @comentario.puntos %>
                  </p>

                  <p>
                    <strong>Usuario:</strong>
                    <%= @comentario.usuario_id %>
                  </p>

                  <p>
                    <strong>Plato:</strong>
                    <%= @comentario.plato_id %>
                  </p>


                </div>
                <ul class="comicNav">
                    <li>
                            

                                <%= link_to 'Editar', edit_comentario_path(@comentario) %>

                           
                        </li>
                        <li>
                            

                                <%= link_to 'Atrás', comentarios_path %>

                            
                        </li>
                </ul>
                <br>


                //ALGÚN COMENTARIO IMPORTANTE


                
                <div id="transcript" style="display: none"></div>
            </div>

           
            
        </body>
        <!--

         Layout by Ian Clasbey, davean, and chromakode 

        -->
    </html>