config/routes.rb
Rails.application.routes.draw do

  resource :user_sessions

  root 'user_sessions#new'

  get 'login' => 'user_sessions#new', :as => :login

  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :acompanamientos

  get 'welcome' => 'welcome#index', :as => :welcome

  resources :usuarios

  resources :sodas

  resources :snacks

  resources :platos

  resources :comentarios

end

app/models/plato.rb
class Plato < ActiveRecord::Base
end

app/controllers/platos_controller.rb
class PlatosController < ApplicationController
  before_action :set_plato, only: [:show, :edit, :update, :destroy]

  # GET /platos
  # GET /platos.json
  def index
    @platos = Plato.all.order(:soda_id).order(:semana).order(:dia).order(:categoria)
  end

  # GET /platos/1
  # GET /platos/1.json
  def show
  end

  # GET /platos/new
  def new
    @plato = Plato.new
  end

  # GET /platos/1/edit
  def edit
  end

  # POST /platos
  # POST /platos.json
  def create
    @plato = Plato.new(plato_params)
    @plato.calificaciones = 0
    @plato.total = 0
    @plato.promedio = 0

    respond_to do |format|
      if @plato.save
        format.html { redirect_to @plato, notice: 'Plato was successfully created.' }
        format.json { render :show, status: :created, location: @plato }
      else
        format.html { render :new }
        format.json { render json: @plato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /platos/1
  # PATCH/PUT /platos/1.json
  def update
    respond_to do |format|
      if @plato.update(plato_params)
        format.html { redirect_to @plato, notice: 'Plato was successfully updated.' }
        format.json { render :show, status: :ok, location: @plato }
      else
        format.html { render :edit }
        format.json { render json: @plato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /platos/1
  # DELETE /platos/1.json
  def destroy
    @plato.destroy
    respond_to do |format|
      format.html { redirect_to platos_url, notice: 'Plato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plato
      @plato = Plato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plato_params
      params.require(:plato).permit(:nombre, :precio, :categoria, :tipo, :calificaciones, :total, :semana, :dia, :soda_id)
    end
end

app/helpers/platos_helper.rb
module PlatosHelper

  def idtostring(number)
    idsToStrings = {"1" => "Odontología", "2" => "Derecho",
                    "3" => "Economía", "4" => "Agronomía", 
                    "5" => "Generales", "6" => "Educación",
                    "7" => "Sociales", "8" => "Comedor"}
    idsToStrings[number.to_s]
  end

  def numtodia(number)
    numToDia = {"1" => "Lunes", "2" => "Martes", "3" => "Miércoles", "4" => "Jueves", "5" => "Viernes", "6" => "Sábado"}
    numToDia[number.to_s]
  end

end

app/views/platos/_form.html.erb
<%= form_for(@plato) do |f| %>
  <% if @plato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plato.errors.count, "error") %> prohibited this plato from being saved:</h2>

      <ul>
      <% @plato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.number_field :precio %>
  </div>
  <div class="field">
    <%= f.label :categoria %><br>
    <%=f.select :categoria, options_for_select([["Básico 1", "Básico 1"], ["Básico 2", "Básico 2"], ["Vegetariano", "Vegetariano"]])%>
  </div>
  <!--div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%=f.label :calificaciones %><br>
    <%= f.number_field :calificaciones %>
  </div>
  <div class="field">
    <%= f.label :total %><br>
    <%= f.number_field :total %>
  </div-->
  <div class="field">
    <%= f.label :soda_id %><br>
    <%=f.select :soda_id, options_for_select([["Odontología", "1"], ["Derecho", "2"], ["Economía", "3"], ["Agronomía", "4"], ["Generales", "5"], ["Educación", "6"], ["Sociales", "7"], ["Comedor", "8"]])%>
  </div>
  <div class="field">
    <%= f.label :semana %><br>
    <%= f.number_field :semana %>
  </div>
  <div class="field">
    <%= f.label :dia %><br>
    <%=f.select :dia, options_for_select([["Lunes", "1"], ["Martes", "2"], ["Miércoles", "3"], ["Jueves", "4"], ["Viernes", "5"], ["Sábado", "6"]])%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/platos/edit.html.erb
    <!--

    ?xml version="1.0" encoding="UTF-8" ?

    -->
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
    <html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" version="-//W3C//DTD XHTML 1.1//EN">
        <head>
            <link title="Default" href="/s/b0dcca.css" type="text/css" rel="stylesheet"></link>
            <title></title>
            <meta content="IE=edge" http-equiv="X-UA-Compatible"></meta>
            <link type="image/x-icon" href="/s/919f27.ico" rel="shortcut icon"></link>
            <link type="image/x-icon" href="/s/919f27.ico" rel="icon"></link>
            <%= stylesheet_link_tag "xkcd.css" %>
            <link href="/atom.xml" title="Atom 1.0" type="application/atom+xml" rel="alternate"></link>
            <link href="/rss.xml" title="RSS 2.0" type="application/rss+xml" rel="alternate"></link>
            <script async="" src="//www.google-analytics.com/analytics.js"></script>
            <script></script>
            <script src="//xkcd.com/1350/jquery.min.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/json2.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/cdn_time.js" type="text/javascript"></script>
            <style type="text/css"></style>
        </head>
        <body>
            <div id="topContainer">
                <div id="topLeft">
                    <ul>
                        <li>
                            <a href="/archive">

                                <%= link_to 'Sodas', sodas_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://what-if.xkcd.com">

                                <%= link_to 'Platos', platos_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://blag.xkcd.com">

                                <%= link_to 'Snacks', snacks_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://store.xkcd.com/">

                                <%= link_to 'Comentarios', comentarios_path %>

                            </a>
                        </li>
                        <li>
                            <a href="/about" rel="author">

                                <%= link_to 'Usuarios', usuarios_path %>

                            </a>
                        </li>
                        <li>

                                <%= link_to 'Extras', acompanamientos_path %>

                        </li>
                    </ul>
                </div>
                <div id="topRight">
                    <div id="masthead">
                        <span>                                
                           <!--img width="185" height="83" alt="xkcd.com logo" src="http://imgs.xkcd.com/static/terrible_small_logo.png"-->
                           <%= link_to(image_tag("UmenU 1.png", size: "185x120"), welcome_path) %>
                        </span>
                        <span id="slogan">

                            ¿No sabés dónde comer?

                            <br>

                             ¡Encontrá algo acá!

                        </span>
                    </div>
                    <div id="news">
                        
                    </div>
                </div>
                <div id="bgLeft" class="bg box"></div>
                <div id="bgRight" class="bg box"></div>
            </div>
            <div id="middleContainer" class="box">
                <div id="ctitle">

                    Editar plato

                </div>
                
                <div id="comic">
                  <%= render 'form' %>
                </div>
                <ul class="comicNav">
                    <li>

                            <%= link_to 'Mostrar', @plato %>
                    </li>
                    <li>

                            <%= link_to 'Atrás', platos_path %>
                    </li>
                </ul>
                <br>


                //ALGÚN MENSAJE IMPORTANTE


                
                <div id="transcript" style="display: none"></div>
            </div>

           
            
        </body>
        <!--

         Layout by Ian Clasbey, davean, and chromakode 

        -->
    </html>

app/views/platos/index.html.erb
    <!--

    ?xml version="1.0" encoding="UTF-8" ?

    -->
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
    <html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" version="-//W3C//DTD XHTML 1.1//EN">
        <head>
            <link title="Default" href="/s/b0dcca.css" type="text/css" rel="stylesheet"></link>
            <title></title>
            <meta content="IE=edge" http-equiv="X-UA-Compatible"></meta>
            <link type="image/x-icon" href="/s/919f27.ico" rel="shortcut icon"></link>
            <link type="image/x-icon" href="/s/919f27.ico" rel="icon"></link>
            <%= stylesheet_link_tag "xkcd.css" %>
            <link href="/atom.xml" title="Atom 1.0" type="application/atom+xml" rel="alternate"></link>
            <link href="/rss.xml" title="RSS 2.0" type="application/rss+xml" rel="alternate"></link>
            <script async="" src="//www.google-analytics.com/analytics.js"></script>
            <script></script>
            <script src="//xkcd.com/1350/jquery.min.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/json2.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/cdn_time.js" type="text/javascript"></script>
            <style type="text/css"></style>
        </head>
        <body>
            <div id="topContainer">
                <div id="topLeft">
                    <ul>
                        <li>
                            <a href="/archive">

                                <%= link_to 'Sodas', sodas_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://what-if.xkcd.com">

                                <%= link_to 'Platos', platos_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://blag.xkcd.com">

                                <%= link_to 'Snacks', snacks_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://store.xkcd.com/">

                                <%= link_to 'Comentarios', comentarios_path %>

                            </a>
                        </li>
                        <li>
                            <a href="/about" rel="author">

                                <%= link_to 'Usuarios', usuarios_path %>

                            </a>
                        </li>
                        <li>

                                <%= link_to 'Extras', acompanamientos_path %>

                        </li>
                    </ul>
                </div>
                <div id="topRight">
                    <div id="masthead">
                        <span>                                
                           <!--img width="185" height="83" alt="xkcd.com logo" src="http://imgs.xkcd.com/static/terrible_small_logo.png"-->
                           <%= link_to(image_tag("UmenU 1.png", size: "185x120"), welcome_path) %>
                        </span>
                        <span id="slogan">

                            ¿No sabés dónde comer?

                            <br>

                             ¡Encontrá algo acá!

                        </span>
                    </div>
                    <div id="news">
                        
                    </div>
                </div>
                <div id="bgLeft" class="bg box"></div>
                <div id="bgRight" class="bg box"></div>
            </div>
            <div id="middleContainer" class="box">
                <div id="ctitle">

                    Platos

                </div>
                
                <div id="comic">
                  <table>
                    <thead>
                      <tr>
                        <th>Nombre</th>
                        <th>Precio</th>
                        <th>Categoria</th>
                        <!--th>Tipo</th-->
                        <th>Calificaciones</th>
                        <th>Total</th>
                        <th>Soda</th>
                        <th>Semana</th>
                        <th>Día</th>
                        <th colspan="3"></th>
                      </tr>
                    </thead>
                
                    <tbody>
                    <% @platos.each do |plato| %>
                      <tr>
                        <td><%= plato.nombre %></td>
                        <td><%= plato.precio %></td>
                        <td><%= plato.categoria %></td>
                        <!--td><%= plato.tipo %></td-->
                        <td><%= plato.calificaciones %></td>
                        <td><%= plato.total %></td>
                        <td><%= idtostring(plato.soda_id) %></td>
                        <td><%= plato.semana %></td>
                        <td><%= numtodia(plato.dia) %></td>
                        <td><%= link_to 'Mostrar', plato %></td>
                        <td><%= link_to 'Editar', edit_plato_path(plato) %></td>
                        <td><%= link_to 'Borrar', plato, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                      </tr>
                    <% end %>
                    </tbody>
                  </table>
                </div>
                <ul class="comicNav">
                    <li>

                            <%= link_to 'Ingresar plato', new_plato_path %>
                    </li>
                </ul>
                <br>


                //ALGÚN MENSAJE IMPORTANTE


                
                <div id="transcript" style="display: none"></div>
            </div>

           
            
        </body>
        <!--

         Layout by Ian Clasbey, davean, and chromakode 

        -->
    </html>

app/views/platos/new.html.erb
    <!--

    ?xml version="1.0" encoding="UTF-8" ?

    -->
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
    <html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" version="-//W3C//DTD XHTML 1.1//EN">
        <head>
            <link title="Default" href="/s/b0dcca.css" type="text/css" rel="stylesheet"></link>
            <title></title>
            <meta content="IE=edge" http-equiv="X-UA-Compatible"></meta>
            <link type="image/x-icon" href="/s/919f27.ico" rel="shortcut icon"></link>
            <link type="image/x-icon" href="/s/919f27.ico" rel="icon"></link>
            <%= stylesheet_link_tag "xkcd.css" %>
            <link href="/atom.xml" title="Atom 1.0" type="application/atom+xml" rel="alternate"></link>
            <link href="/rss.xml" title="RSS 2.0" type="application/rss+xml" rel="alternate"></link>
            <script async="" src="//www.google-analytics.com/analytics.js"></script>
            <script></script>
            <script src="//xkcd.com/1350/jquery.min.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/json2.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/cdn_time.js" type="text/javascript"></script>
            <style type="text/css"></style>
        </head>
        <body>
            <div id="topContainer">
                <div id="topLeft">
                    <ul>
                        <li>
                            <a href="/archive">

                                <%= link_to 'Sodas', sodas_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://what-if.xkcd.com">

                                <%= link_to 'Platos', platos_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://blag.xkcd.com">

                                <%= link_to 'Snacks', snacks_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://store.xkcd.com/">

                                <%= link_to 'Comentarios', comentarios_path %>

                            </a>
                        </li>
                        <li>
                            <a href="/about" rel="author">

                                <%= link_to 'Usuarios', usuarios_path %>

                            </a>
                        </li>
                        <li>

                                <%= link_to 'Extras', acompanamientos_path %>

                        </li>
                    </ul>
                </div>
                <div id="topRight">
                    <div id="masthead">
                        <span>                                
                           <!--img width="185" height="83" alt="xkcd.com logo" src="http://imgs.xkcd.com/static/terrible_small_logo.png"-->
                           <%= link_to(image_tag("UmenU 1.png", size: "185x120"), welcome_path) %>
                        </span>
                        <span id="slogan">

                            ¿No sabés dónde comer?

                            <br>

                             ¡Encontrá algo acá!

                        </span>
                    </div>
                    <div id="news">
                        
                    </div>
                </div>
                <div id="bgLeft" class="bg box"></div>
                <div id="bgRight" class="bg box"></div>
            </div>
            <div id="middleContainer" class="box">
                <div id="ctitle">

                    Nuevo plato

                </div>
                
                <div id="comic">
                  <%= render 'form' %>
                </div>
                <ul class="comicNav">
                    <li>

                            <%= link_to 'Atrás', platos_path %>
                    </li>
                </ul>
                <br>


                //ALGÚN MENSAJE IMPORTANTE


                
                <div id="transcript" style="display: none"></div>
            </div>

           
            
        </body>
        <!--

         Layout by Ian Clasbey, davean, and chromakode 

        -->
    </html>

app/views/platos/show.html.erb
    <!--

    ?xml version="1.0" encoding="UTF-8" ?

    -->
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
    <html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" version="-//W3C//DTD XHTML 1.1//EN">
        <head>
            <link title="Default" href="/s/b0dcca.css" type="text/css" rel="stylesheet"></link>
            <title></title>
            <meta content="IE=edge" http-equiv="X-UA-Compatible"></meta>
            <link type="image/x-icon" href="/s/919f27.ico" rel="shortcut icon"></link>
            <link type="image/x-icon" href="/s/919f27.ico" rel="icon"></link>
            <%= stylesheet_link_tag "xkcd.css" %>
            <link href="/atom.xml" title="Atom 1.0" type="application/atom+xml" rel="alternate"></link>
            <link href="/rss.xml" title="RSS 2.0" type="application/rss+xml" rel="alternate"></link>
            <script async="" src="//www.google-analytics.com/analytics.js"></script>
            <script></script>
            <script src="//xkcd.com/1350/jquery.min.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/json2.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/cdn_time.js" type="text/javascript"></script>
            <style type="text/css"></style>
        </head>
        <body>
            <div id="topContainer">
                <div id="topLeft">
                    <ul>
                        <li>
                            <a href="/archive">

                                <%= link_to 'Sodas', sodas_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://what-if.xkcd.com">

                                <%= link_to 'Platos', platos_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://blag.xkcd.com">

                                <%= link_to 'Snacks', snacks_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://store.xkcd.com/">

                                <%= link_to 'Comentarios', comentarios_path %>

                            </a>
                        </li>
                        <li>
                            <a href="/about" rel="author">

                                <%= link_to 'Usuarios', usuarios_path %>

                            </a>
                        </li>
                        <li>

                                <%= link_to 'Extras', acompanamientos_path %>

                        </li>
                    </ul>
                </div>
                <div id="topRight">
                    <div id="masthead">
                        <span>                                
                           <!--img width="185" height="83" alt="xkcd.com logo" src="http://imgs.xkcd.com/static/terrible_small_logo.png"-->
                           <%= link_to(image_tag("UmenU 1.png", size: "185x120"), welcome_path) %>
                        </span>
                        <span id="slogan">

                            ¿No sabés dónde comer?

                            <br>

                             ¡Encontrá algo acá!

                        </span>
                    </div>
                    <div id="news">
                        
                    </div>
                </div>
                <div id="bgLeft" class="bg box"></div>
                <div id="bgRight" class="bg box"></div>
            </div>
            <div id="middleContainer" class="box">
                <div id="ctitle">

                    Plato

                </div>
                
                <div id="comic">
                    <p>
                      <strong>Nombre:</strong>
                      <%= @plato.nombre %>                    
                    </p>

                    <p>
                      <strong>Precio:</strong>
                      <%= @plato.precio %>
                    </p>

                    <p>
                      <strong>Categoria:</strong>
                      <%= @plato.categoria %>
                    </p>

                    <!--p>
                      <strong>Tipo:</strong>
                      <%= @plato.tipo %>
                    </p-->
                    
                    <p>
                      <strong>Calificaciones:</strong>
                      <%= @plato.calificaciones %>
                    </p>
                    
                    <p>
                      <strong>Total:</strong>
                      <%= @plato.total %>
                    </p>

                    <p>
                      <strong>Soda:</strong>
                      <%= idtostring(@plato.soda_id) %>
                    </p>

                    <p>
                      <strong>Semana:</strong>
                      <%= @plato.semana %>
                    </p>

                    <p>
                      <strong>Día:</strong>
                      <%= numtodia(@plato.dia) %>
                    </p>
                </div>
                <ul class="comicNav">
                    <li>

                            <%= link_to 'Editar', edit_plato_path(@plato) %>

                    </li>
                    <li>

                            <%= link_to 'Atrás', platos_path %>
                    </li>
                </ul>
                <br>


                //ALGÚN MENSAJE IMPORTANTE


                
                <div id="transcript" style="display: none"></div>
            </div>

           
            
        </body>
        <!--

         Layout by Ian Clasbey, davean, and chromakode 

        -->
    </html>



<%= link_to 'Edit', edit_plato_path(@plato) %>
<%= link_to 'Back', platos_path %>