config/routes.rb
Rails.application.routes.draw do

  resource :user_sessions

  root 'user_sessions#new'

  get 'login' => 'user_sessions#new', :as => :login

  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :acompanamientos

  get 'welcome' => 'welcome#index', :as => :welcome

  resources :usuarios

  resources :sodas

  resources :snacks

  resources :platos

  resources :comentarios

end

app/models/soda.rb
class Soda < ActiveRecord::Base
end

app/controllers/sodas_controller.rb
class SodasController < ApplicationController
  before_action :set_soda, only: [:show, :edit, :update, :destroy]

  # GET /sodas
  # GET /sodas.json
  def index
    @sodas = Soda.all
  end

  # GET /sodas/1
  # GET /sodas/1.json
  def show
  end

  # GET /sodas/new
  def new
    @soda = Soda.new
  end

  # GET /sodas/1/edit
  def edit
  end

  # POST /sodas
  # POST /sodas.json
  def create
    @soda = Soda.new(soda_params)

    respond_to do |format|
      if @soda.save
        format.html { redirect_to @soda, notice: 'Soda was successfully created.' }
        format.json { render :show, status: :created, location: @soda }
      else
        format.html { render :new }
        format.json { render json: @soda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sodas/1
  # PATCH/PUT /sodas/1.json
  def update
    respond_to do |format|
      if @soda.update(soda_params)
        format.html { redirect_to @soda, notice: 'Soda was successfully updated.' }
        format.json { render :show, status: :ok, location: @soda }
      else
        format.html { render :edit }
        format.json { render json: @soda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sodas/1
  # DELETE /sodas/1.json
  def destroy
    @soda.destroy
    respond_to do |format|
      format.html { redirect_to sodas_url, notice: 'Soda was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_soda
      @soda = Soda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def soda_params
      params.require(:soda).permit(:nombre, :long, :lat, :descripcion)
    end
end

app/helpers/sodas_helper.rb
module SodasHelper
end

app/views/sodas/_form.html.erb
<%= form_for(@soda) do |f| %>
  <% if @soda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@soda.errors.count, "error") %> prohibited this soda from being saved:</h2>

      <ul>
      <% @soda.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :long %><br>
    <%= f.text_field :long %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sodas/edit.html.erb
    <!--

    ?xml version="1.0" encoding="UTF-8" ?

    -->
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
    <html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" version="-//W3C//DTD XHTML 1.1//EN">
        <head>
            <link title="Default" href="/s/b0dcca.css" type="text/css" rel="stylesheet"></link>
            <title></title>
            <meta content="IE=edge" http-equiv="X-UA-Compatible"></meta>
            <link type="image/x-icon" href="/s/919f27.ico" rel="shortcut icon"></link>
            <link type="image/x-icon" href="/s/919f27.ico" rel="icon"></link>
            <%= stylesheet_link_tag "xkcd.css" %>
            <link href="/atom.xml" title="Atom 1.0" type="application/atom+xml" rel="alternate"></link>
            <link href="/rss.xml" title="RSS 2.0" type="application/rss+xml" rel="alternate"></link>
            <script async="" src="//www.google-analytics.com/analytics.js"></script>
            <script></script>
            <script src="//xkcd.com/1350/jquery.min.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/json2.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/cdn_time.js" type="text/javascript"></script>
            <style type="text/css"></style>
        </head>
        <body>
            <div id="topContainer">
                <div id="topLeft">
                    <ul>
                        <li>
                            <a href="/archive">

                                <%= link_to 'Sodas', sodas_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://what-if.xkcd.com">

                                <%= link_to 'Platos', platos_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://blag.xkcd.com">

                                <%= link_to 'Snacks', snacks_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://store.xkcd.com/">

                                <%= link_to 'Comentarios', comentarios_path %>

                            </a>
                        </li>
                        <li>
                            <a href="/about" rel="author">

                                <%= link_to 'Usuarios', usuarios_path %>

                            </a>
                        </li>
                        <li>

                                <%= link_to 'Extras', acompanamientos_path %>

                        </li>
                    </ul>
                </div>
                <div id="topRight">
                    <div id="masthead">
                        <span>                                
                           <!--img width="185" height="83" alt="xkcd.com logo" src="http://imgs.xkcd.com/static/terrible_small_logo.png"-->
                           <%= link_to(image_tag("UmenU 1.png", size: "185x120"), welcome_path) %>
                        </span>
                        <span id="slogan">

                            ¿No sabés dónde comer?

                            <br>

                             ¡Encontrá algo acá!

                        </span>
                    </div>
                    <div id="news">
                        
                    </div>
                </div>
                <div id="bgLeft" class="bg box"></div>
                <div id="bgRight" class="bg box"></div>
            </div>
            <div id="middleContainer" class="box">
                <div id="ctitle">

                    Editar soda

                </div>
                
                <div id="comic">
                    <%= render 'form' %>
                </div>
                <ul class="comicNav">
                    <li>

                            <%= link_to 'Mostrar', @soda %> 
                    </li>
                    <li>

                            <%= link_to 'Atrás', sodas_path %>
                    </li>
                </ul>
                <br>


                //ALGÚN MENSAJE IMPORTANTE


                
                <div id="transcript" style="display: none"></div>
            </div>

           
            
        </body>
        <!--

         Layout by Ian Clasbey, davean, and chromakode 

        -->
    </html>

app/views/sodas/index.html.erb
    <!--

    ?xml version="1.0" encoding="UTF-8" ?

    -->
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
    <html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" version="-//W3C//DTD XHTML 1.1//EN">
        <head>
            <link title="Default" href="/s/b0dcca.css" type="text/css" rel="stylesheet"></link>
            <title></title>
            <meta content="IE=edge" http-equiv="X-UA-Compatible"></meta>
            <link type="image/x-icon" href="/s/919f27.ico" rel="shortcut icon"></link>
            <link type="image/x-icon" href="/s/919f27.ico" rel="icon"></link>
            <%= stylesheet_link_tag "xkcd.css" %>
            <link href="/atom.xml" title="Atom 1.0" type="application/atom+xml" rel="alternate"></link>
            <link href="/rss.xml" title="RSS 2.0" type="application/rss+xml" rel="alternate"></link>
            <script async="" src="//www.google-analytics.com/analytics.js"></script>
            <script></script>
            <script src="//xkcd.com/1350/jquery.min.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/json2.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/cdn_time.js" type="text/javascript"></script>
            <style type="text/css"></style>
        </head>
        <body>
            <div id="topContainer">
                <div id="topLeft">
                    <ul>
                        <li>
                            <a href="/archive">

                                <%= link_to 'Sodas', sodas_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://what-if.xkcd.com">

                                <%= link_to 'Platos', platos_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://blag.xkcd.com">

                                <%= link_to 'Snacks', snacks_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://store.xkcd.com/">

                                <%= link_to 'Comentarios', comentarios_path %>

                            </a>
                        </li>
                        <li>
                            <a href="/about" rel="author">

                                <%= link_to 'Usuarios', usuarios_path %>

                            </a>
                        </li>
                        <li>

                                <%= link_to 'Extras', acompanamientos_path %>

                        </li>
                    </ul>
                </div>
                <div id="topRight">
                    <div id="masthead">
                        <span>                                
                           <!--img width="185" height="83" alt="xkcd.com logo" src="http://imgs.xkcd.com/static/terrible_small_logo.png"-->
                           <%= link_to(image_tag("UmenU 1.png", size: "185x120"), welcome_path) %>
                        </span>
                        <span id="slogan">

                            ¿No sabés dónde comer?

                            <br>

                             ¡Encontrá algo acá!

                        </span>
                    </div>
                    <div id="news">
                        
                    </div>
                </div>
                <div id="bgLeft" class="bg box"></div>
                <div id="bgRight" class="bg box"></div>
            </div>
            <div id="middleContainer" class="box">
                <div id="ctitle">

                    Sodas

                </div>
                
                <div id="comic">
                    <table>
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Descripción</th>
                                <th>Latitud</th>
                                <th>Longitud</th>
                                <th colspan="3"></th>
                            </tr>
                        </thead>

                        <tbody>
                            <% @sodas.each do |soda| %>
                            <tr>
                                <td><%= soda.nombre %></td>
                                <td><%= soda.descripcion %></td>
                                <td><%= soda.lat %></td>
                                <td><%= soda.long %></td>
                                <td><%= link_to 'Mostrar', soda %></td>
                                <td><%= link_to 'Editar', edit_soda_path(soda) %></td>
                                <td><%= link_to 'Borrar', soda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                           </tr>
                           <% end %>
                       </tbody>
                   </table>
                </div>
                <ul class="comicNav">
                    <li>

                            <%= link_to 'Ingresar soda', new_soda_path %>
                    </li>
                </ul>
                <br>


                //ALGÚN MENSAJE IMPORTANTE


                
                <div id="transcript" style="display: none"></div>
            </div>

           
            
        </body>
        <!--

         Layout by Ian Clasbey, davean, and chromakode 

        -->
    </html-->

app/views/sodas/new.html.erb
    <!--

    ?xml version="1.0" encoding="UTF-8" ?

    -->
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
    <html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" version="-//W3C//DTD XHTML 1.1//EN">
        <head>
            <link title="Default" href="/s/b0dcca.css" type="text/css" rel="stylesheet"></link>
            <title></title>
            <meta content="IE=edge" http-equiv="X-UA-Compatible"></meta>
            <link type="image/x-icon" href="/s/919f27.ico" rel="shortcut icon"></link>
            <link type="image/x-icon" href="/s/919f27.ico" rel="icon"></link>
            <%= stylesheet_link_tag "xkcd.css" %>
            <link href="/atom.xml" title="Atom 1.0" type="application/atom+xml" rel="alternate"></link>
            <link href="/rss.xml" title="RSS 2.0" type="application/rss+xml" rel="alternate"></link>
            <script async="" src="//www.google-analytics.com/analytics.js"></script>
            <script></script>
            <script src="//xkcd.com/1350/jquery.min.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/json2.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/cdn_time.js" type="text/javascript"></script>
            <style type="text/css"></style>
        </head>
        <body>
            <div id="topContainer">
                <div id="topLeft">
                    <ul>
                        <li>
                            <a href="/archive">

                                <%= link_to 'Sodas', sodas_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://what-if.xkcd.com">

                                <%= link_to 'Platos', platos_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://blag.xkcd.com">

                                <%= link_to 'Snacks', snacks_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://store.xkcd.com/">

                                <%= link_to 'Comentarios', comentarios_path %>

                            </a>
                        </li>
                        <li>
                            <a href="/about" rel="author">

                                <%= link_to 'Usuarios', usuarios_path %>

                            </a>
                        </li>
                        <li>

                                <%= link_to 'Extras', acompanamientos_path %>

                        </li>
                    </ul>
                </div>
                <div id="topRight">
                    <div id="masthead">
                        <span>                                
                           <!--img width="185" height="83" alt="xkcd.com logo" src="http://imgs.xkcd.com/static/terrible_small_logo.png"-->
                           <%= link_to(image_tag("UmenU 1.png", size: "185x120"), welcome_path) %>
                        </span>
                        <span id="slogan">

                            ¿No sabés dónde comer?

                            <br>

                             ¡Encontrá algo acá!

                        </span>
                    </div>
                    <div id="news">
                        
                    </div>
                </div>
                <div id="bgLeft" class="bg box"></div>
                <div id="bgRight" class="bg box"></div>
            </div>
            <div id="middleContainer" class="box">
                <div id="ctitle">

                    Nueva soda

                </div>
                
                <div id="comic">
                    <%= render 'form' %>
                </div>
                <ul class="comicNav">
                    <li>

                            <%= link_to 'Atrás', sodas_path %>
                    </li>
                </ul>
                <br>


                //ALGÚN MENSAJE IMPORTANTE


                
                <div id="transcript" style="display: none"></div>
            </div>

           
            
        </body>
        <!--

         Layout by Ian Clasbey, davean, and chromakode 

        -->
    </html>

app/views/sodas/show.html.erb
    <!--

    ?xml version="1.0" encoding="UTF-8" ?

    -->
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
    <html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" version="-//W3C//DTD XHTML 1.1//EN">
        <head>
            <link title="Default" href="/s/b0dcca.css" type="text/css" rel="stylesheet"></link>
            <title></title>
            <meta content="IE=edge" http-equiv="X-UA-Compatible"></meta>
            <link type="image/x-icon" href="/s/919f27.ico" rel="shortcut icon"></link>
            <link type="image/x-icon" href="/s/919f27.ico" rel="icon"></link>
            <%= stylesheet_link_tag "xkcd.css" %>
            <link href="/atom.xml" title="Atom 1.0" type="application/atom+xml" rel="alternate"></link>
            <link href="/rss.xml" title="RSS 2.0" type="application/rss+xml" rel="alternate"></link>
            <script async="" src="//www.google-analytics.com/analytics.js"></script>
            <script></script>
            <script src="//xkcd.com/1350/jquery.min.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/json2.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/cdn_time.js" type="text/javascript"></script>
            <style type="text/css"></style>
        </head>
        <body>
            <div id="topContainer">
                <div id="topLeft">
                    <ul>
                        <li>
                            <a href="/archive">

                                <%= link_to 'Sodas', sodas_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://what-if.xkcd.com">

                                <%= link_to 'Platos', platos_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://blag.xkcd.com">

                                <%= link_to 'Snacks', snacks_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://store.xkcd.com/">

                                <%= link_to 'Comentarios', comentarios_path %>

                            </a>
                        </li>
                        <li>
                            <a href="/about" rel="author">

                                <%= link_to 'Usuarios', usuarios_path %>

                            </a>
                        </li>
                        <li>

                                <%= link_to 'Extras', acompanamientos_path %>

                        </li>
                    </ul>
                </div>
                <div id="topRight">
                    <div id="masthead">
                        <span>                                
                           <!--img width="185" height="83" alt="xkcd.com logo" src="http://imgs.xkcd.com/static/terrible_small_logo.png"-->
                           <%= link_to(image_tag("UmenU 1.png", size: "185x120"), welcome_path) %>
                        </span>
                        <span id="slogan">

                            ¿No sabés dónde comer?

                            <br>

                             ¡Encontrá algo acá!

                        </span>
                    </div>
                    <div id="news">
                        
                    </div>
                </div>
                <div id="bgLeft" class="bg box"></div>
                <div id="bgRight" class="bg box"></div>
            </div>
            <div id="middleContainer" class="box">
                <div id="ctitle">

                    Soda <%= @soda.nombre %> 

                </div>
                
                <div id="comic">
                    <p>
                        <strong>Nombre:</strong>
                        <%= @soda.nombre %> 
                    </p>

                    <p>
                        <strong>Descripción:</strong>
                        <%= @soda.descripcion %>
                    </p>

                    <p>
                        <strong>Latitud:</strong>
                        <%= @soda.lat %>
                    </p>

                    <p>
                        <strong>Longitud:</strong>
                        <%= @soda.long %>
                    </p>
                </div>
                <ul class="comicNav">
                    <li>

                            <%= link_to 'Editar', edit_soda_path(@soda) %>
                    </li>
                    <li>

                            <%= link_to 'Atrás', sodas_path %>
                    </li>
                </ul>
                <br>


                //ALGÚN MENSAJE IMPORTANTE


                
                <div id="transcript" style="display: none"></div>
            </div>

           
            
        </body>
        <!--

         Layout by Ian Clasbey, davean, and chromakode 

        -->
    </html>