config/routes.rb
Rails.application.routes.draw do

  resource :user_sessions

  root 'user_sessions#new'

  get 'login' => 'user_sessions#new', :as => :login

  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :acompanamientos

  get 'welcome' => 'welcome#index', :as => :welcome

  resources :usuarios

  resources :sodas

  resources :snacks

  resources :platos

  resources :comentarios

end

app/models/snack.rb
class Snack < ActiveRecord::Base
end

app/controllers/snacks_controller.rb
class SnacksController < ApplicationController
  before_action :set_snack, only: [:show, :edit, :update, :destroy]

  # GET /snacks
  # GET /snacks.json
  def index
    @snacks = Snack.all
  end

  # GET /snacks/1
  # GET /snacks/1.json
  def show
  end

  # GET /snacks/new
  def new
    @snack = Snack.new
  end

  # GET /snacks/1/edit
  def edit
  end

  # POST /snacks
  # POST /snacks.json
  def create
    @snack = Snack.new(snack_params)

    respond_to do |format|
      if @snack.save
        format.html { redirect_to @snack, notice: 'Snack was successfully created.' }
        format.json { render :show, status: :created, location: @snack }
      else
        format.html { render :new }
        format.json { render json: @snack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snacks/1
  # PATCH/PUT /snacks/1.json
  def update
    respond_to do |format|
      if @snack.update(snack_params)
        format.html { redirect_to @snack, notice: 'Snack was successfully updated.' }
        format.json { render :show, status: :ok, location: @snack }
      else
        format.html { render :edit }
        format.json { render json: @snack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snacks/1
  # DELETE /snacks/1.json
  def destroy
    @snack.destroy
    respond_to do |format|
      format.html { redirect_to snacks_url, notice: 'Snack was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snack
      @snack = Snack.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snack_params
      params.require(:snack).permit(:nombre, :precio, :soda_id)
    end
end

app/helpers/snacks_helper.rb
module SnacksHelper

  def idtostring(number)
    idsToStrings = {"1" => "Odontología", "2" => "Derecho",
                    "3" => "Economía", "4" => "Agronomía", 
                    "5" => "Generales", "6" => "Educación",
                    "7" => "Sociales", "8" => "Comedor"}
    idsToStrings[number.to_s]
  end

end

app/views/snacks/_form.html.erb
<%= form_for(@snack) do |f| %>
  <% if @snack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snack.errors.count, "error") %> prohibited this snack from being saved:</h2>

      <ul>
      <% @snack.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.number_field :precio %>
  </div>
  <div class="field">
    <%= f.label :soda_id %><br>
    <%= f.number_field :soda_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/snacks/edit.html.erb
    <!--

    ?xml version="1.0" encoding="UTF-8" ?

    -->
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
    <html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" version="-//W3C//DTD XHTML 1.1//EN">
        <head>
            <link title="Default" href="/s/b0dcca.css" type="text/css" rel="stylesheet"></link>
            <title></title>
            <meta content="IE=edge" http-equiv="X-UA-Compatible"></meta>
            <link type="image/x-icon" href="/s/919f27.ico" rel="shortcut icon"></link>
            <link type="image/x-icon" href="/s/919f27.ico" rel="icon"></link>
            <%= stylesheet_link_tag "xkcd.css" %>
            <link href="/atom.xml" title="Atom 1.0" type="application/atom+xml" rel="alternate"></link>
            <link href="/rss.xml" title="RSS 2.0" type="application/rss+xml" rel="alternate"></link>
            <script async="" src="//www.google-analytics.com/analytics.js"></script>
            <script></script>
            <script src="//xkcd.com/1350/jquery.min.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/json2.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/cdn_time.js" type="text/javascript"></script>
            <style type="text/css"></style>
        </head>
        <body>
            <div id="topContainer">
                <div id="topLeft">
                    <ul>
                        <li>
                            <a href="/archive">

                                <%= link_to 'Sodas', sodas_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://what-if.xkcd.com">

                                <%= link_to 'Platos', platos_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://blag.xkcd.com">

                                <%= link_to 'Snacks', snacks_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://store.xkcd.com/">

                                <%= link_to 'Comentarios', comentarios_path %>

                            </a>
                        </li>
                        <li>
                            <a href="/about" rel="author">

                                <%= link_to 'Usuarios', usuarios_path %>

                            </a>
                        </li>
                        <li>

                                <%= link_to 'Extras', acompanamientos_path %>

                        </li>
                    </ul>
                </div>
                <div id="topRight">
                    <div id="masthead">
                        <span>                                
                           <!--img width="185" height="83" alt="xkcd.com logo" src="http://imgs.xkcd.com/static/terrible_small_logo.png"-->
                           <%= link_to(image_tag("UmenU 1.png", size: "185x120"), welcome_path) %>
                        </span>
                        <span id="slogan">

                            ¿No sabés dónde comer?

                            <br>

                             ¡Encontrá algo acá!

                        </span>
                    </div>
                    <div id="news">
                        
                    </div>
                </div>
                <div id="bgLeft" class="bg box"></div>
                <div id="bgRight" class="bg box"></div>
            </div>
            <div id="middleContainer" class="box">
                <div id="ctitle">

                    Snack

                </div>
                
                <div id="comic">
                  <%= render 'form' %>

                </div>
                <ul class="comicNav">
                    <li>

                            <%= link_to 'Mostrar', @snack %>
                    </li>
                    <li>

                            <%= link_to 'Atrás', snacks_path %>
                    </li>
                </ul>
                <br>


                //ALGÚN MENSAJE IMPORTANTE


                
                <div id="transcript" style="display: none"></div>
            </div>

           
            
        </body>
        <!--

         Layout by Ian Clasbey, davean, and chromakode 

        -->
    </html>

app/views/snacks/index.html.erb
    <!--

    ?xml version="1.0" encoding="UTF-8" ?

    -->
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
    <html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" version="-//W3C//DTD XHTML 1.1//EN">
        <head>
            <link title="Default" href="/s/b0dcca.css" type="text/css" rel="stylesheet"></link>
            <title></title>
            <meta content="IE=edge" http-equiv="X-UA-Compatible"></meta>
            <link type="image/x-icon" href="/s/919f27.ico" rel="shortcut icon"></link>
            <link type="image/x-icon" href="/s/919f27.ico" rel="icon"></link>
            <%= stylesheet_link_tag "xkcd.css" %>
            <link href="/atom.xml" title="Atom 1.0" type="application/atom+xml" rel="alternate"></link>
            <link href="/rss.xml" title="RSS 2.0" type="application/rss+xml" rel="alternate"></link>
            <script async="" src="//www.google-analytics.com/analytics.js"></script>
            <script></script>
            <script src="//xkcd.com/1350/jquery.min.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/json2.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/cdn_time.js" type="text/javascript"></script>
            <style type="text/css"></style>
        </head>
        <body>
            <div id="topContainer">
                <div id="topLeft">
                    <ul>
                        <li>
                            <a href="/archive">

                                <%= link_to 'Sodas', sodas_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://what-if.xkcd.com">

                                <%= link_to 'Platos', platos_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://blag.xkcd.com">

                                <%= link_to 'Snacks', snacks_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://store.xkcd.com/">

                                <%= link_to 'Comentarios', comentarios_path %>

                            </a>
                        </li>
                        <li>
                            <a href="/about" rel="author">

                                <%= link_to 'Usuarios', usuarios_path %>

                            </a>
                        </li>
                        <li>

                                <%= link_to 'Extras', acompanamientos_path %>

                        </li>
                    </ul>
                </div>
                <div id="topRight">
                    <div id="masthead">
                        <span>                                
                           <!--img width="185" height="83" alt="xkcd.com logo" src="http://imgs.xkcd.com/static/terrible_small_logo.png"-->
                           <%= link_to(image_tag("UmenU 1.png", size: "185x120"), welcome_path) %>
                        </span>
                        <span id="slogan">

                            ¿No sabés dónde comer?

                            <br>

                             ¡Encontrá algo acá!

                        </span>
                    </div>
                    <div id="news">
                        
                    </div>
                </div>
                <div id="bgLeft" class="bg box"></div>
                <div id="bgRight" class="bg box"></div>
            </div>
            <div id="middleContainer" class="box">
                <div id="ctitle">

                    Snacks

                </div>
                
                <div id="comic">
                  <table>
                    <thead>
                      <tr>
                        <th>Nombre</th>
                        <th>Precio</th>
                        <th>Soda</th>
                        <th colspan="3"></th>
                      </tr>
                    </thead>

                    <tbody>
                      <% @snacks.each do |snack| %>
                        <tr>
                          <td><%= snack.nombre %></td>
                          <td><%= snack.precio %></td>
                          <td><%= idtostring(snack.soda_id)%></td>
                          <td><%= link_to 'Mostrar', snack %></td>
                          <td><%= link_to 'Editar', edit_snack_path(snack) %></td>
                          <td><%= link_to 'Borrar', snack, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
                <ul class="comicNav">
                    <li>

                            <%= link_to 'Ingresar snack', new_snack_path %>
                    </li>
                </ul>
                <br>


                //ALGÚN MENSAJE IMPORTANTE


                
                <div id="transcript" style="display: none"></div>
            </div>

           
            
        </body>
        <!--

         Layout by Ian Clasbey, davean, and chromakode 

        -->
    </html>

app/views/snacks/new.html.erb
    <!--

    ?xml version="1.0" encoding="UTF-8" ?

    -->
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
    <html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" version="-//W3C//DTD XHTML 1.1//EN">
        <head>
            <link title="Default" href="/s/b0dcca.css" type="text/css" rel="stylesheet"></link>
            <title></title>
            <meta content="IE=edge" http-equiv="X-UA-Compatible"></meta>
            <link type="image/x-icon" href="/s/919f27.ico" rel="shortcut icon"></link>
            <link type="image/x-icon" href="/s/919f27.ico" rel="icon"></link>
            <%= stylesheet_link_tag "xkcd.css" %>
            <link href="/atom.xml" title="Atom 1.0" type="application/atom+xml" rel="alternate"></link>
            <link href="/rss.xml" title="RSS 2.0" type="application/rss+xml" rel="alternate"></link>
            <script async="" src="//www.google-analytics.com/analytics.js"></script>
            <script></script>
            <script src="//xkcd.com/1350/jquery.min.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/json2.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/cdn_time.js" type="text/javascript"></script>
            <style type="text/css"></style>
        </head>
        <body>
            <div id="topContainer">
                <div id="topLeft">
                    <ul>
                        <li>
                            <a href="/archive">

                                <%= link_to 'Sodas', sodas_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://what-if.xkcd.com">

                                <%= link_to 'Platos', platos_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://blag.xkcd.com">

                                <%= link_to 'Snacks', snacks_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://store.xkcd.com/">

                                <%= link_to 'Comentarios', comentarios_path %>

                            </a>
                        </li>
                        <li>
                            <a href="/about" rel="author">

                                <%= link_to 'Usuarios', usuarios_path %>

                            </a>
                        </li>
                        <li>

                                <%= link_to 'Extras', acompanamientos_path %>

                        </li>
                    </ul>
                </div>
                <div id="topRight">
                    <div id="masthead">
                        <span>                                
                           <!--img width="185" height="83" alt="xkcd.com logo" src="http://imgs.xkcd.com/static/terrible_small_logo.png"-->
                           <%= link_to(image_tag("UmenU 1.png", size: "185x120"), welcome_path) %>
                        </span>
                        <span id="slogan">

                            ¿No sabés dónde comer?

                            <br>

                             ¡Encontrá algo acá!

                        </span>
                    </div>
                    <div id="news">
                        
                    </div>
                </div>
                <div id="bgLeft" class="bg box"></div>
                <div id="bgRight" class="bg box"></div>
            </div>
            <div id="middleContainer" class="box">
                <div id="ctitle">

                    Nuevo snack

                </div>
                
                <div id="comic">
                  <%= render 'form' %>

                </div>
                <ul class="comicNav">
                    <li>

                            <%= link_to 'Atrás', snacks_path %>
                    </li>
                </ul>
                <br>


                //ALGÚN MENSAJE IMPORTANTE


                
                <div id="transcript" style="display: none"></div>
            </div>

           
            
        </body>
        <!--

         Layout by Ian Clasbey, davean, and chromakode 

        -->
    </html>

app/views/snacks/show.html.erb
    <!--

    ?xml version="1.0" encoding="UTF-8" ?

    -->
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
    <html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" version="-//W3C//DTD XHTML 1.1//EN">
        <head>
            <link title="Default" href="/s/b0dcca.css" type="text/css" rel="stylesheet"></link>
            <title></title>
            <meta content="IE=edge" http-equiv="X-UA-Compatible"></meta>
            <link type="image/x-icon" href="/s/919f27.ico" rel="shortcut icon"></link>
            <link type="image/x-icon" href="/s/919f27.ico" rel="icon"></link>
            <%= stylesheet_link_tag "xkcd.css" %>
            <link href="/atom.xml" title="Atom 1.0" type="application/atom+xml" rel="alternate"></link>
            <link href="/rss.xml" title="RSS 2.0" type="application/rss+xml" rel="alternate"></link>
            <script async="" src="//www.google-analytics.com/analytics.js"></script>
            <script></script>
            <script src="//xkcd.com/1350/jquery.min.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/json2.js" type="text/javascript"></script>
            <script src="//xkcd.com/static/cdn_time.js" type="text/javascript"></script>
            <style type="text/css"></style>
        </head>
        <body>
            <div id="topContainer">
                <div id="topLeft">
                    <ul>
                        <li>
                            <a href="/archive">

                                <%= link_to 'Sodas', sodas_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://what-if.xkcd.com">

                                <%= link_to 'Platos', platos_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://blag.xkcd.com">

                                <%= link_to 'Snacks', snacks_path %>

                            </a>
                        </li>
                        <li>
                            <a href="http://store.xkcd.com/">

                                <%= link_to 'Comentarios', comentarios_path %>

                            </a>
                        </li>
                        <li>
                            <a href="/about" rel="author">

                                <%= link_to 'Usuarios', usuarios_path %>

                            </a>
                        </li>
                        <li>

                                <%= link_to 'Extras', acompanamientos_path %>

                        </li>
                    </ul>
                </div>
                <div id="topRight">
                    <div id="masthead">
                        <span>                                
                           <!--img width="185" height="83" alt="xkcd.com logo" src="http://imgs.xkcd.com/static/terrible_small_logo.png"-->
                           <%= link_to(image_tag("UmenU 1.png", size: "185x120"), welcome_path) %>
                        </span>
                        <span id="slogan">

                            ¿No sabés dónde comer?

                            <br>

                             ¡Encontrá algo acá!

                        </span>
                    </div>
                    <div id="news">
                        
                    </div>
                </div>
                <div id="bgLeft" class="bg box"></div>
                <div id="bgRight" class="bg box"></div>
            </div>
            <div id="middleContainer" class="box">
                <div id="ctitle">

                    Snack

                </div>
                
                <div id="comic">
                  <p>
                    <strong>Nombre:</strong>
                    <%= @snack.nombre %>
                  </p>

                  <p>
                    <strong>Precio:</strong>
                    <%= @snack.precio %>
                  </p>

                  <p>
                    <strong>Soda:</strong>
                    <%=idtostring(@snack.soda_id)%>
                  </p>

                </div>
                <ul class="comicNav">
                    <li>

                            <%= link_to 'Editar', edit_snack_path(@snack) %>
                    </li>
                    <li>

                            <%= link_to 'Atrás', snacks_path %>
                    </li>
                </ul>
                <br>


                //ALGÚN MENSAJE IMPORTANTE


                
                <div id="transcript" style="display: none"></div>
            </div>

           
            
        </body>
        <!--

         Layout by Ian Clasbey, davean, and chromakode 

        -->
    </html>